version: "3.5"
services:
    mysql:
        image: mysql
        ports:
            - 3306:3306
        env_file:
            - .env
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
        volumes:
            - ./setup.sql:/docker-entrypoint-initdb.d/setup.sql
